import 'package:flutter/material.dart';
import 'package:flutterapp/facepalm_messagingappapp/generatedframe16widget/generated/GeneratedSettingWidget2.dart';
import 'package:flutterapp/facepalm_messagingappapp/generatedframe16widget/generated/GeneratedDatahaschangedWidget.dart';
import 'package:flutterapp/facepalm_messagingappapp/generatedframe16widget/generated/GeneratedLogoutAkunWidget2.dart';
import 'package:flutterapp/facepalm_messagingappapp/generatedframe16widget/generated/GeneratedRectangle28Widget2.dart';
import 'package:flutterapp/facepalm_messagingappapp/generatedframe16widget/generated/GeneratedRectangle28Widget3.dart';
import 'package:flutterapp/facepalm_messagingappapp/generatedframe16widget/generated/GeneratedLogoutWidget2.dart';
import 'package:flutterapp/facepalm_messagingappapp/generatedframe16widget/generated/Generated5445440422_backarrowicontransparentpngclipartfreedownlo2.dart';
import 'package:flutterapp/facepalm_messagingappapp/generatedframe16widget/generated/GeneratedRectangle27Widget2.dart';

/* Frame Frame 16
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame16Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedFrame12Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 411.0,
          height: 823.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 411.0,
                  height: 823.0,
                  child: GeneratedSettingWidget2(),
                ),
                Positioned(
                  left: 0.0,
                  top: 633.7808227539062,
                  right: null,
                  bottom: null,
                  width: 411.0,
                  height: 71.78079986572266,
                  child: GeneratedRectangle27Widget2(),
                ),
                Positioned(
                  left: 5.8212890625,
                  top: 586.3784790039062,
                  right: null,
                  bottom: null,
                  width: 357.1133117675781,
                  height: 27.732738494873047,
                  child: GeneratedLogoutAkunWidget2(),
                ),
                Positioned(
                  left: 321.3486328125,
                  top: 579.6067504882812,
                  right: null,
                  bottom: null,
                  width: 81.50141906738281,
                  height: 35.213218688964844,
                  child: GeneratedRectangle28Widget2(),
                ),
                Positioned(
                  left: 339.9775390625,
                  top: 585.0241088867188,
                  right: null,
                  bottom: null,
                  width: 55.065155029296875,
                  height: 30.732738494873047,
                  child: GeneratedLogoutWidget2(),
                ),
                Positioned(
                  left: 0.0,
                  top: 1.0,
                  right: null,
                  bottom: null,
                  width: 411.0,
                  height: 36.0,
                  child: GeneratedRectangle28Widget3(),
                ),
                Positioned(
                  left: 134.0,
                  top: 10.0,
                  right: null,
                  bottom: null,
                  width: 146.0,
                  height: 21.0,
                  child: GeneratedDatahaschangedWidget(),
                ),
                Positioned(
                  left: 15.0,
                  top: 14.0,
                  right: null,
                  bottom: null,
                  width: 38.095237731933594,
                  height: 29.81884002685547,
                  child:
                      Generated5445440422_backarrowicontransparentpngclipartfreedownlo2(),
                )
              ]),
        ),
      ),
    ));
  }
}
