import 'package:flutter/material.dart';
import 'package:flutterapp/facepalm_messagingappapp/generatedframe4widget/generated/GeneratedChatWidget.dart';
import 'package:flutterapp/facepalm_messagingappapp/generatedframe4widget/generated/GeneratedEllipse4Widget.dart';
import 'package:flutterapp/facepalm_messagingappapp/generatedframe4widget/generated/GeneratedOnlineWidget.dart';
import 'package:flutterapp/facepalm_messagingappapp/generatedframe4widget/generated/GeneratedEllipse3Widget.dart';

/* Frame Frame 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedFrame10Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 411.0,
          height: 823.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 411.0,
                  height: 823.0,
                  child: GeneratedChatWidget(),
                ),
                Positioned(
                  left: 148.0,
                  top: 46.0,
                  right: null,
                  bottom: null,
                  width: 116.0,
                  height: 26.0,
                  child: GeneratedOnlineWidget(),
                ),
                Positioned(
                  left: 148.0,
                  top: 50.0,
                  right: null,
                  bottom: null,
                  width: 14.0,
                  height: 15.0,
                  child: GeneratedEllipse3Widget(),
                ),
                Positioned(
                  left: 64.0,
                  top: 10.0,
                  right: null,
                  bottom: null,
                  width: 70.0,
                  height: 70.0,
                  child: GeneratedEllipse4Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
