description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^0.1.3"
  path_drawing: "^0.4.1"
  flutter: 
    sdk: "flutter"
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.7.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Nunito"
      fonts: 
        - 
          asset: "fonts/Nunito-900.ttf"
          style: "normal"
          weight: 900
        - 
          asset: "fonts/Nunito-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Nunito-300.ttf"
          style: "normal"
          weight: 300
        - 
          asset: "fonts/Nunito-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Numans"
      fonts: 
        - 
          asset: "fonts/Numans-regular.ttf"
          style: "normal"
          weight: 400
  uses-material-design: true
